# Generated by Django 4.1.7 on 2023-02-16 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='First Name', max_length=50)),
                ('last_name', models.CharField(default='Last Name', max_length=50)),
                ('email_address', models.EmailField(default='Email Address', max_length=150)),
                ('password', models.CharField(default='Password', max_length=30)),
                ('cpassword', models.CharField(default='Cpassword', max_length=30)),
                ('main', models.CharField(default='Last Name', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='cpassword',
            field=models.CharField(default='Cpassword', max_length=30),
        ),
        migrations.AddField(
            model_name='person',
            name='email_address',
            field=models.EmailField(default='Email Address', max_length=150),
        ),
        migrations.AddField(
            model_name='person',
            name='password',
            field=models.CharField(default='Password', max_length=30),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(default='First Name', max_length=50),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(default='Last Name', max_length=50),
        ),
    ]
