# Generated by Django 4.1 on 2023-03-17 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_persons_delete_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Persons',
        ),
        migrations.AlterField(
            model_name='person',
            name='cpassword',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='person',
            name='email_address',
            field=models.EmailField(max_length=150),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='person',
            name='password',
            field=models.CharField(max_length=30),
        ),
    ]
